# Generated by Django 3.0.8 on 2020-07-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_auto_20200725_0133"),
    ]

    operations = [
        migrations.RemoveField(model_name="publications", name="update_date",),
    ]
