# Generated by Django 3.0.8 on 2020-07-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_auto_20200725_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="comments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="board.Comments",
                verbose_name="Комментарий",
            ),
        ),
    ]
