# Generated by Django 3.0.8 on 2020-07-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_auto_20200725_1317"),
    ]

    operations = [
        migrations.RemoveField(model_name="publications", name="comments",),
        migrations.DeleteModel(name="Comments",),
    ]
