# Generated by Django 3.0.8 on 2020-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="description",
            field=models.TextField(verbose_name="Комментарий"),
        ),
    ]
