# Generated by Django 3.0.8 on 2020-07-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_auto_20200725_1332"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments", old_name="description", new_name="comment",
        ),
    ]
