# Generated by Django 3.0.8 on 2020-07-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0011_auto_20200725_1400"),
    ]

    operations = [
        migrations.RemoveField(model_name="publications", name="comments",),
        migrations.DeleteModel(name="Comments",),
    ]
